server:
  port: 9901
spring:
  datasource:
    url: jdbc:mysql://rm-bp1035514z9uq43q46o.mysql.rds.aliyuncs.com:3306/pei_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncode=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: admin_1066365803
    password: 142536aA
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 47.120.48.158
    port: 6379
    password: 142536aA
    database: 1
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
pei-blog:
  filePath: /tmp/peiBlog
